# Generated by Django 5.1.5 on 2025-03-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='despesa',
            old_name='descric_desp',
            new_name='desc_desp',
        ),
        migrations.RenameField(
            model_name='receita',
            old_name='descric_rec',
            new_name='desc_rec',
        ),
    ]
